### ISSUE TITLE
missing prepare_prediction in KMeansEngine

### ISSUE THREAD

**Issue by mattf** [rapidsai/scikit-learn-nv#3]
```
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
>>> from sklearn.cluster import KMeans
>>> from sklearn.datasets import make_blobs
>>> 
>>> import cupy as cp
>>> 
>>> X, y_true = make_blobs(
...     n_samples=300, centers=4, n_features=3, cluster_std=0.60, random_state=10
... )
>>> with sklearn.config_context(engine_provider="sklearn_nv"):
...     km = KMeans(random_state=42)
...     km.fit(X)
...     y_pred = km.predict(X)
... 
/home/matt/scikit-learn/sklearn/cluster/_kmeans.py:1049: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
KMeans(random_state=42)
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/matt/scikit-learn/sklearn/cluster/_kmeans.py", line 1705, in predict
    X, sample_weight = engine.prepare_prediction(X, sample_weight)
AttributeError: 'KMeansEngine' object has no attribute 'prepare_prediction'
>>> sklearn.__version__
'1.3.dev0'
```

**Comment by mattf** [comment]
```
$ (cd scikit-learn; git status; git log | head)
On branch feature/engine-api
Your branch is up to date with 'origin/feature/engine-api'.

nothing to commit, working tree clean
commit a897a34d7d989bf317de17f80948639c0fd5ecf1
Author: Olivier Grisel <olivier.grisel@ensta.org>
Date:   Tue Feb 7 11:00:15 2023 +0100

    DOC fix missing info and formatting for get_engine_classes

commit 2fa1489f0927e326af9ad9ccc1344a7401280f1a
Merge: ce78cf482 4acd91d88
Author: Olivier Grisel <olivier.grisel@ensta.org>
Date:   Mon Feb 6 18:29:56 2023 +0100
```

**Comment by jjerphan** [comment]
I can reproduce this bug.

**Comment by jjerphan** [comment]
I confirm that I can reproduce this bug. :+1:
